/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConceptCategory = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'author' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addConceptCategory' : IDL.Func([ConceptCategory], [], []),
  'getAllConceptCategories' : IDL.Func(
      [],
      [IDL.Vec(ConceptCategory)],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConceptCategory = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({ 'author' : IDL.Text, 'message' : IDL.Text });
  
  return IDL.Service({
    'addConceptCategory' : IDL.Func([ConceptCategory], [], []),
    'getAllConceptCategories' : IDL.Func(
        [],
        [IDL.Vec(ConceptCategory)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };